server.port=8083
spring.application.name=hearing-service

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/dvara?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Auto Table Creation
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Actuator Exposure
management.endpoints.web.exposure.include=*
